### ISSUE TITLE
GraphQL API: return branches in reverse order by default

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#119]
So that `main` is the first branch to be returned.

**Comment by didimitrie** [comment]
Looked at this, and this does sound like a thing to do on the frontend, where we can choose sorting: 
- by latest edit
- latest commit
- default to: main first, then the rest

**Comment by teocomi** [comment]
Ideally filtering and sorting would be parameters on most of our gql endpoints! 😄 

The reason for asking this is that we already had sorting logic on the frontend, but the order was getting messed up every time apollo refreshed the query. Sure it can be sorted somehow but, sorting on the backed sounds more proper.
Feel free to close this if you disagree 👍

**Comment by teocomi** [comment]
Resolution: it was decided not to change the order of the branches.

**Comment by didimitrie** [comment]
It was decided to return branches with `main` first, and then the rest, rather than in the "last updated" order that's there currently (currently it's a deceiving sorting criteria, as last updated here means last "edited", rather than last committed at - the latter could be implemented easily though). 

Nevertheless, this kind-of screws up the existing query on the sql-side of things, so this will entail rethinking pagination somehow; or removing it completely. Removing it **might** be dangerous for first-time api users as they could create quite a massive n+1 graphql query (all the branches and the first 100 commits from each), but perhaps this isn't a big concern.
