### ISSUE TITLE
Affinity rule to ensure server and frontend-2 are deployed to the same node

### ISSUE THREAD

**Issue by iainsproat** [specklesystems/speckle-server#1460]
We should have a pod affinity rule to try to ensure server and frontend-2 are deployed to the same node. (though this won't scale)

**Comment by fabis94** [comment]
Reason: If `server` and `frontend-2` are close to each other and the latency between them is low, then the server-side render by `frontend-2` will be fairly quick and the experience will be improved for our users. This is because on first load the user only receives pure HTML with all of the GQL calls already pre-made on the server-side.
