### ISSUE TITLE
Viewer Explode Mode: Centre Refresh

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#1561]
Minor issue: when swapping one version of a model to another the viewer explodes around the first loaded world bbox center, and not an updated one. 

I might be wrong, can demo :)

**Comment by AlexandruPopovici** [comment]
In this commit: https://github.com/specklesystems/speckle-server/commit/a8a43497d20b806bc74dac2e75f696a508301cf7

The World wasn't being reduced after removing subtrees. That's fixed now, but I can't be sure this was the root cause for the bug you described since I've ran it in the sandbox, where streams load in/out differently than in FE2
