### ISSUE TITLE
Bug: Speckle Viewer Flickering 

### ISSUE THREAD

**Issue by emilaz** [specklesystems/speckle-server#1751]
## Describe the bug

Hi, I'm working with a sample Revit MEP project with a linked IFC file (both around 10MB in size). 
I'm using the Speckle Revit Connector 2.15.2.
There are both Rooms in the IFC file as well as MEP spaces in the main model, if that makes a difference.

I'm transferring all data, including from the linked model, to my Speckle Server. When viewing the commit in the Speckle Viewer, the rooms exhibit very strong graphical "flickering". When I toggle visibility of Spaces off, the flickering stops almost completely (except for the doors and windows, which for some reason flicker as well. 

I tried:
- Different computer (Mac and WIndows)
- Different browser (Firefox and Safari)
- Several commits.

I can share the link to the commit/stream if required.

## To Reproduce

1. Use a simple Revit architecture model, create architecture rooms, save to IFC (not sure if this makes a difference, but alas)
2. Link IFC into a new MEP Revit project, create MEP spaces in main model
3. Send the main model plus linked model to Speckle server, view on speckle website in speckle viewer.

## Expected behavior

No flickering :) 

## Screenshots

A snapshot of the flickering 
![image](https://github.com/specklesystems/speckle-server/assets/29956128/eb599be0-7908-4322-ba2e-c005cd1f33de)

### Desktop (please complete the following information):

- Browser: Firefox, Safari
- System: Windows, Mac

**Comment by AlexandruPopovici** [comment]
Hi @emilaz 

Thanks for the report. Could you possibly share a stream which exhibits the issue your describing. I have suspicion why you are seeing this behavior, but I want to check first to be sure

Thanks

**Comment by didimitrie** [comment]
Hi @emilaz: this is unfortunately expected behaviour. The spaces from the ifc import are overlapping with the rest of the geometry. Here's [a link with them turned off - no more flickering](https://speckle.xyz/streams/d83996a7f8/commits/90ecb134ea?filter=%7B%22hiddenIds%22%3A%5B%2228727df947aaa46cda65edcc8db6765a%22,%223986f0b2c17a8398648ad9adf6bd08ea%22,%22251215557bb63a0732fd7953f0333d50%22,%22da1cc1871f8c2483b37ceffdafae965c%22,%22db976c9eb1b269e52fb30b18f2b27b98%22,%2299db9e59d0ec1e3c46a4e90f409dcbdf%22,%223d0a83882efe127c289f8f597f74105d%22,%2253a063c6d330b9bb2f5170064cca47fc%22,%2252bc0d19254ee2f71fb1196990d5af15%22,%22e52f8ccd29ff54335541b7f1012a521c%22,%225477eacb1ba55486c91dff5be9e1b25d%22,%224bcc9ce6d7c68b0195f4e9f9f626dd11%22,%2235c6244f75f946c97a24e2fdf0337fb2%22,%225a9a5c38d0fff181eeb8232cf7216df5%22,%2250fde072510de90040e733384eea8c72%22,%22510e10efe313abeeec175d1c6cd8e3d7%22,%2283d8eee6ff6dfb17afd1b0b9e330da7d%22,%22bddfe0b39f006fa0b4cd694cf73813d0%22%5D,%22propertyInfoKey%22%3A%22speckle_type%22,%22sectionBox%22%3A%5B-13.25,-4,-5.77,13.8,9.64,1.49%5D%7D&c=%5B-12.14816,-7.5909,11.82306,-5.07449,3.03068,0.52131,0,1%5D).

Would you expect them to be hidden by default?

**Comment by emilaz** [comment]
Ah that makes sense. I think it might cause some confusion for people as to why this flickering occurs, but at the same it it might not be a smart idea to just filter out elements on the user's behalf without being explicit about it?
Don't have a strong opinion here tbh - but thanks for clearing this up!
