### ISSUE TITLE
Frontend: Add "embed viewer" functionality

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#197]
Would be nice to be able to embed the viewer as an iFrame anywhere.

This would be dependent on the stream being public, or attaching some token to the url maybe??

We could also add a handy button on the stream page to copy embed code (iframe, url...) just like youtube does

**Comment by didimitrie** [comment]
discussion notes with @AlanRynne: 
- append an ?embed=true url query that the renderer picks up and goes automatically in full screen
- add Powered by Speckle (tm) because 😎 
- add View in Speckle -> sends you to the actual server
- remove the exit fullscreen button
- add fancy share button with iframe embed code stuff in viewer toolbar (or around)

**Comment by AlanRynne** [comment]
Was not linked properly but this was merged in #242
