### ISSUE TITLE
Public Stream / Link sharing alignment

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#237]
There are various references in our UIs and docs to "sharing streams via URL", but now changing that setting actually makes a stream "public" and visible even without the link (just head to a user's profile).

We should update frontend, connector UIs and docs.

**Comment by didimitrie** [comment]
I've updated this in the frontend already actually 😎 (you can check it on latest, should be up there since a day or so).

![image](https://user-images.githubusercontent.com/7696515/118006510-38ad6300-b343-11eb-8c47-0b9417a6f189.png)

and

![image](https://user-images.githubusercontent.com/7696515/118006586-49f66f80-b343-11eb-8bb8-334b33cea658.png)

I'll close this issue here and raise one in docs/admin for our connector uis and docs.

**Comment by teocomi** [comment]
I think we should get rid of the "link sharing" expression altogether and replace it with "private/public". We should also update the icon with something more appropriate. 
There's also a few references in the docs that needs updating!
