### ISSUE TITLE
Frontend: Admin panel warning if user is not admin doesn't show up correctly

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#334]
the warning flashes but disappears

![admin-panel-weirdness](https://user-images.githubusercontent.com/7717434/125430365-d54525c3-8c69-4b4a-ae82-04240169ce1c.gif)

**Comment by izzylys** [comment]
also sometimes shows up when it shouldn't

![admin-panel-weirdness-2](https://user-images.githubusercontent.com/7717434/125430929-9240e493-639b-4c93-a31d-622d05b98a23.gif)

**Comment by AlanRynne** [comment]
Ok found a fix for this :) Turns out it was Apollo throwing a weird error while trying to cache the results of the user query (because i was just querying the `role` it was failing)
Possible fix on the way: Add the id to the query to allow apollo to distinguish them.
Also, the loading state was not properly setup either.

Thanks for catching this! I'll have a PR ready in a bit
