### ISSUE TITLE
Previews: Ignore commits on Globals branch when showing preview of last commit

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-server#338]
- [x] In the `/preview/:streamId` endpoint, when getting the last commit on that stream, we should ignore commits on the `globals` branch.

- [x] Also, the frontend's main page should use `/preview/:streamId` endpoint to show previews instead of getting the last commit and use the `/preview/:streamId/objects/:objectId/:angle` endpoint

**Comment by cristi8** [comment]
@didimitrie should i do a more deep change?

I am thinking of changing the service function `getCommitsByStreamId` to ignore the `globals` branch.
This function is also used to get the gql `stream -> commits` and `stream -> commit` 

Are there scenarios when we want to include the `globals` commits?

**Comment by didimitrie** [comment]
That can break several things in clients (make globals undiscoverable, and we rely on the same mechansism to get objects from the globals branch as we do for all other commits, e.g. in grasshopper). I'd settle for the superficial change at the moment until we have time to weigh this properly. 

I'm writing this with 10% of my brain, will rope @izzylys in...

**Comment by izzylys** [comment]
to clarify re endpoint changes, the idea would be that you could only ever see globals commits when specifically requesting the `globals` branch?

imo this is too deep of a change atm since the feature may evolve, so hardcoding at the server level seems premature. i also think that if globals are used on a stream, they're gonna be p important and it's likely you'd want to see them in the list of recent commits either in the frontend recent activity or in your scripts.

i think the changes to the `/preview` endpoint make the most sense
