### ISSUE TITLE
NODE_ENV getting set to `development'` by server run script

### ISSUE THREAD

**Issue by parkerjgit** [specklesystems/speckle-server#780]
**What package are you referring to?**
server

**Describe the bug**
Changes made to dev run script here: https://github.com/specklesystems/speckle-server/commit/0ac118e05c837d6440824442fdb93a60864daa41#diff-92fadee1dfb23b20d6b0f6557a3ea0b8a231a7591db73f9f37772383bd0575d9 result in NODE_ENV getting set to `development'` instead of `development`, which results in type error during knex initialization b/c configs[env] is undefined:

![1](https://user-images.githubusercontent.com/1270665/170882419-d78e0cdd-f507-4321-aafe-73b0cefeca96.JPG)

reverting changes fixes issue for me.

```
"dev": "cross-env NODE_ENV=development DEBUG=speckle:* nodemon ./bin/www --watch . --watch ./bin/www  -e js,graphql,env"
```

**To Reproduce**
```
docker-compose -f docker-compose-deps.yml up -d
cp .env-example .env
npm i --force
npm run dev
```

**Expected behavior**
dev server starts successfully

**Comment by gjedlicska** [comment]
Hey @parkerjgit,

thanks for reporting this. Its been fixed in #785 .

Also please take a look at our updated dev docs. We've recently migrated away from using `npm` and now we rely on `yarn` to manage the monorepo project. All in all things should be a lot smoother on the development experience side compared to the old `lerna + npm` approach, but it requires a tiny bit of getting used to.
