### ISSUE TITLE
Profile Page + Stream Visibility Changes

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#961]
## What package are you referring to?

Server + FE

## Describe the solution you'd like

Currently, link sharable streams are visible on users' profile pages. With the introduction of discoverable streams in #948, this becomes redundant.

Proposed changes: 

1) the `user(id) { streams { /*...*/ } }` query should return only a users's discoverable streams + any shared streams with the logged in user (if present). 

2) make a user's profile page public (currently it is visible only if you are logged in).

**Comment by fabis94** [comment]
@didimitrie The 2nd point is quite sketchy, especially considering this: https://github.com/specklesystems/admin/issues/330. What I mean is that guests being able to request user data will be another thing to keep in mind and potentially forget when sculpting User type fields.

It's quite a big departure from how we've worked with the User type up till now, because this will mean unregistered users will now be able to get all kinds of information about registered users. Not necessarily anything private like the email, but especially on invite-only servers I can see server owners not wanting to leak anything about their users.

If you want, I can still proceed with this and try to go over all User fields to check whether all of them are set up securely, but personally I'd wait till we can move all non-authenticated-user queries to the LimitedUser type instead, cause then it'll be easier to manage.

**Comment by fabis94** [comment]
Here's the PR: https://github.com/specklesystems/speckle-server/pull/1002

For now I've just implemented point 1 and refactored the tests, let me know how I should continue
